### ISSUE TITLE
data-uri does not honor a page local images-dir

### ISSUE THREAD

**Issue by hferentschik** [asciidoctor/asciidoctor#2278]
I am running a Middleman site using the middleman-asciidoc plugin. I have the following layout:

    /dir1/a.adoc
            /b.adoc
            /images
    dir2/c.adoc
           /images

So basically I want to have my image directory per sub-folder (opposed to a single global images dir). I could not find an option or easy way to configure Middleman to do so, but adding 
    
     :imagesdir: ./images

to the individual adoc pages makes things work. At least when serving the images via links. I can create the site and all works as expected.

Now I want to add the data-uri attribute as well:

    :data-uri:
    :imagesdir: ./images

Now when I render the page, I am getting warning messages that the images cannot be found. The path printed is the path to the image relative to the "global" images-dir. For all I can tell data-uri is ignoring the locally specified images-dir. 

This might be an issue of the Middleman plugin as well, but I thought I start reporting here. Any ideas? Where is the code driving the data-uri processing?

**Comment by hferentschik** [comment]
The message is:

    asciidoctor: WARNING: image to embed not found or not readable: <path to image, relative to global images dir>

**Comment by mojavelinux** [comment]
When the processor visits and image macro and the data-uri attribute is set, it immediately resolves the path to the image. Unlike when data-uri is not set, this path must be a system path. How that system path is resolved depends on what the "base" directory is. The base directory is irrelevant when resolving web paths, but significant when resolving system paths.

If you're using Middleman 4, the base directory should match the document directory. Therefore, the resolved system path will be docdir + imagesdir.

If you are not using Middleman 4, or you have set the base_dir in your configuration to the source directory, then the resolved system path will be sourcedir + imagesdir (which is what you are observing).

It's important that the base directory track the location of the document or else relative paths won't work.

This is definitely a Middleman AsciiDoc issue, not a core issue.

**Comment by hferentschik** [comment]
> If you're using Middleman 4

I am using Middleman 4

>  the base directory should match the document directory

Right, you pointed me into the right direction. I actually had custom Middleman::Extension to tweak the base dir. Something like this:

     app.config[:asciidoc][:base_dir] = app.source_dir

Luckily I don't need this anymore. Now that I removed it it works.

> It's important that the base directory track the location of the document or else relative paths won't work.

Hmm, I find it is still not quite right. IMO I should be able to set a global image dir and then per doc override this. Is this not officially supported? If so, I would argue that that _data-uri_ should be able to handle this as well. 

For me part it works now. Feel free to close this issue, if you think all is as it should.

**Comment by mojavelinux** [comment]
> IMO I should be able to set a global image dir and then per doc override this.

You can do that by appending an `@` to the value where you set it in the site configuration. The `@` is a special flag that makes the attribute value overridable.

Can you make that work?
